
package com.oracle.custom.asc.callout;

import java.util.List;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(portName = "ManagementPort", serviceName = "ManagementService", targetNamespace = "http://www.acmepacket.com/asc/ws/mgmt", wsdlLocation = "/wsdls/AcmePacketASCManagement.wsdl", endpointInterface = "com.oracle.custom.asc.callout.ManagementPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class ManagementService_ManagementPortImpl
    implements ManagementPortType
{


    public ManagementService_ManagementPortImpl() {
    }

    /**
     * 
     *                 This operation provides access to all or some of the active
     *                 configuration from the Net-Net Application Session Controller platform.
     *             
     * 
     * @param path
     * @param config
     * @throws Fault_Exception
     */
    public void getConfig(Holder<List<ConfigClassesType>> config, List<String> path)
        throws Fault_Exception
    {
        //replace with your impl here
        return;
    }

    /**
     * 
     *                 This operation allows the active configuration on the Net-Net Application Session Controller
     *                 platform to be altered.
     *             
     * 
     * @param parameters
     * @return
     *     returns com.oracle.custom.asc.callout.SetConfigResponseType
     * @throws Fault_Exception
     */
    public SetConfigResponseType setConfig(SetConfigType parameters)
        throws Fault_Exception
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     *                 This operation retrieves one or more collections of active
     *                 status from the Net-Net Application Session Controller platform.
     *             
     * 
     * @param status
     * @throws Fault_Exception
     */
    public void getStatus(Holder<List<StatusClassesType>> status)
        throws Fault_Exception
    {
        //replace with your impl here
        return;
    }

    /**
     * 
     *                 This operation queries one or more collections of active
     *                 status from the Net-Net Application Session Controller platform.
     *             
     * 
     * @param status
     * @throws Fault_Exception
     */
    public void queryStatus(Holder<List<StatusClassesType>> status)
        throws Fault_Exception
    {
        //replace with your impl here
        return;
    }

    /**
     * 
     *                 This operation will invoke an action on the Net-Net Application Session Controller platforms.
     *                 Actions are defined commands that the Net-Net Application Session Controller can execute.
     *             
     * 
     * @param parameters
     * @return
     *     returns com.oracle.custom.asc.callout.DoActionResponseType
     * @throws Fault_Exception
     */
    public DoActionResponseType doAction(DoActionType parameters)
        throws Fault_Exception
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     *                 This operation will invoke an action on the Net-Net Application Session Controller platforms.
     *                 Actions are defined commands that the Net-Net Application Session Controller can execute.
     *                 This means of invoking action can return extended data.
     *             
     * 
     * @param parameters
     * @return
     *     returns com.oracle.custom.asc.callout.ActionResultsType
     * @throws Fault_Exception
     */
    public ActionResultsType doActionEx(DoActionType parameters)
        throws Fault_Exception
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     *                 This operation will return the authorization information for the
     *                 user that has logged into the session that is making this request.
     *             
     * 
     * @return
     *     returns com.oracle.custom.asc.callout.AuthorizedUserType
     * @throws Fault_Exception
     */
    public AuthorizedUserType getAuthorization()
        throws Fault_Exception
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     *                 This operation will upload a file to the ASC
     *             
     * 
     * @param parameters
     * @return
     *     returns com.oracle.custom.asc.callout.UploadFileResponseType
     * @throws Fault_Exception
     */
    public UploadFileResponseType uploadFile(UploadFileType parameters)
        throws Fault_Exception
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     *                 This operation will download a file to the ASC
     *             
     * 
     * @param parameters
     * @return
     *     returns com.oracle.custom.asc.callout.DownloadFileResponseType
     * @throws Fault_Exception
     */
    public DownloadFileResponseType downloadFile(DownloadFileType parameters)
        throws Fault_Exception
    {
        //replace with your impl here
        return null;
    }

}
